title: Gabby’s Cookbook
description: CookLang recipes
theme: minima
markdown: kramdown
collections:
  recipes_generated:
    output: true
defaults:
  - scope:
      path: "_recipes_generated"
    values:
      layout: recipe
