name: Generate recipe .md files

on:
  push:
    branches: [main]
    paths:
      - "recipes/**/*.cook"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate Markdown from .cook files
        run: |
          mkdir -p _recipes_generated
          rm -f _recipes_generated/*.md
          find recipes -type f -name '*.cook' | while read -r f; do
            name=$(basename "$f" .cook)
            out="_recipes_generated/$name.md"
            {
              echo "---"
              echo "layout: recipe"
              echo "title: ${name//_/ }"
              echo "---"
              echo ""
              echo '```cooklang'
              cat "$f"
              echo '```'
            } > "$out"
          done

      - name: Commit generated markdown
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: vinxa@github.com
          message: Auto-generate markdown recipes
          add: '_recipes_generated/* --force'
          pathspec_error_handling: ignore